server:
    port: 8080
eureka:
    server:
        enable-self-preservaion: false
    instance:
        preferIpAddress: true
        hostname: localhost
        instanceId: localhost:${server.port}
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
