eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/
spring:
    application:
        name: work
management:
    endpoints:
        web:
            exposure:
                include: refresh, health, info
server:
    port: 8084
