eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/ ##注册中心默认地址
server:
    port: 8083
spring:
    application:
        name: feign  ##应用名称
# 开启熔断器
feign:
    hystrix:
        enabled: true